In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as  plt
import seaborn as sns

In [6]:
df = pd.read_csv("../data/raw/ai4i2020.csv")
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [7]:
# for visualization data ProfilingReport

In [8]:
# %pip install -q ydata-profiling
from ydata_profiling import ProfileReport

In [9]:
profile = ProfileReport(df, title="Pandas Profiling Report", explorative=True)

In [10]:
profile.to_file("../data/processed/ai4i2020.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

%|                                                                                           | 0/14 [00:00<?, ?it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 91.30it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [11]:
df.head()

df.tail()
df.sample(5)

df.shape

df.columns

df.info()

df.describe()

df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), object(2)
memory usage: 1.1+ MB

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
count,10000.00000,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
unique,NaN,10000,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,L57163,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,5000.50000,NaN,NaN,300.004930,310.005560,1538.776100,39.986910,107.951000,0.033900,0.004600,0.011500,0.009500,0.009800,0.00190
std,2886.89568,NaN,NaN,2.000259,1.483734,179.284096,9.968934,63.654147,0.180981,0.067671,0.106625,0.097009,0.098514,0.04355
min,1.00000,NaN,NaN,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,NaN,NaN,298.300000,308.800000,1423.000000,33.200000,53.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,5000.50000,NaN,NaN,300.100000,310.100000,1503.000000,40.100000,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7500.25000,NaN,NaN,301.500000,311.100000,1612.000000,46.800000,162.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,10000.00000,NaN,NaN,304.500000,313.800000,2886.000000,76.600000,253.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

In [12]:
df['Machine failure'].value_counts()

Machine failure
0    9661
1     339
Name: count, dtype: int64

In [13]:
df['Machine failure'].value_counts()/100

Machine failure
0    96.61
1     3.39
Name: count, dtype: float64

In [14]:
# sns.countplot(x=df['Machine failure'])
sns.countplot(data=df,x='Machine failure')

plt.title("Machine Failure Distribution")

Text(0.5, 1.0, 'Machine Failure Distribution')

In [15]:
sns.countplot(data=df,x=df['Type'])

In [16]:
sns.countplot(data=df,x='Type',hue=df['Machine failure'])

In [17]:
failure_counts = df[["TWF","HDF","PWF","OSF","RNF"]].sum()

failure_counts.plot(kind='bar')

plt.title("Failure Type Distribution")

plt.ylabel("Count")

Text(0, 0.5, 'Count')

In [18]:
df.columns

Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF',
       'RNF'],
      dtype='object')

In [19]:
cols =[
    "Air temperature [K]",
    "Process temperature [K]",
    "Rotational speed [rpm]",
    "Torque [Nm]",
    "Tool wear [min]"
]

for col in cols:
    sns.displot(df[col], kde=True)

In [20]:
# box plot (outliers)

for col in cols:
    plt.figure()
    sns.boxplot(x=df[col])

In [21]:
sns.scatterplot(data=df,x=df['Rotational speed [rpm]'], y=df['Torque [Nm]'],hue=df['Machine failure'])

In [22]:
# missing value
df.isnull().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

In [23]:
df.fillna(df.mean(numeric_only=True))

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,0,0,0,0,0
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,0,0,0,0,0
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,0,0,0,0,0
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,0,0,0,0,0
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,0,0,0,0,0

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
# if duplicate so:
df.drop_duplicates()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,0,0,0,0,0
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,0,0,0,0,0
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,0,0,0,0,0
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,0,0,0,0,0
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,0,0,0,0,0

In [26]:
df.shape

(10000, 14)

In [27]:
df.sample(5)

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
5434,5435,L52614,L,302.9,312.5,1629,30.4,74,0,0,0,0,0,0
7270,7271,L54450,L,300.2,310.4,1808,25.8,35,0,0,0,0,0,0
5061,5062,L52241,L,304.0,312.9,1363,62.5,200,1,0,0,0,1,0
4974,4975,L52154,L,303.8,312.7,1414,41.7,190,0,0,0,0,0,0
368,369,L47548,L,297.5,308.4,1489,39.5,96,0,0,0,0,0,0

In [28]:
# # uid and productID are not used so remove:
df.drop(['UDI','Product ID'],axis=1,inplace=True)

In [29]:
df.sample(2)

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
4191,L,302.4,311.0,1317,59.4,179,0,0,0,0,0,0
2683,L,299.8,309.5,1590,28.5,23,0,0,0,0,0,0

In [30]:
# check outliers
numeric_col =  df.select_dtypes('number')
numeric_col.columns

for col in numeric_col:
    plt.figure()
    
    sns.boxplot(x=df[col])

C:\Users\manav\AppData\Local\Temp\ipykernel_18756\24876704.py:6: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()

In [31]:
# for above boxplot 
# outliers = [Rotational speed [rpm],Torque [Nm]] in this columns

In [32]:
# remove outliers from both columns

out_clo = ['Rotational speed [rpm]','Torque [Nm]']

for col in out_clo:
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3- Q1
     
    min = Q1 - 1.5 * IQR
    max = Q3 + 1.5 * IQR
    
    # (df[col] >= min) & (df[col] <= max)  this give bool dataframe
    
    df = df[(df[col] >= min) & (df[col] <= max)]

In [33]:
# after remove it further plot both boxplot

for col in out_clo:
    
    plt.figure()
    
    sns.boxplot(x=df[col])

In [34]:
remove_outliers = df.copy()

In [35]:
remove_outliers.shape

(9535, 12)

In [36]:
# save new data (remove_outliers_data)

remove_outliers.to_csv("../data/processed/remove_outliers_data.csv")

In [37]:
df.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [38]:
# Ordinal Encoding on Type column
from sklearn.preprocessing import OrdinalEncoder

df_type = df.iloc[:,0:1]
df_type

en = OrdinalEncoder(categories=[['L','M','H']])

df['Type'] = en.fit_transform(df_type)

In [39]:
df['Type'] = df['Type'].astype(int)

In [40]:
df.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,0,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,0,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,0,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,0,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [41]:
ordinal_encoding_type_data = df.copy()

In [42]:
ordinal_encoding_type_data.to_csv("../data/processed/ordinal_encoding_type_data.csv")

In [43]:
df.columns

Index(['Type', 'Air temperature [K]', 'Process temperature [K]',
       'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]',
       'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF'],
      dtype='object')

In [44]:
df.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,0,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,0,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,0,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,0,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [45]:
df.shape

(9535, 12)

In [46]:
df_classification = df.drop(columns=['TWF','HDF','PWF','OSF','RNF'])

In [47]:
df_classification.to_csv('../data/processed/df_classification_data')

In [48]:
df_classification.columns

Index(['Type', 'Air temperature [K]', 'Process temperature [K]',
       'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]',
       'Machine failure'],
      dtype='object')

In [49]:
df_classification

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,1,298.1,308.6,1551,42.8,0,0
1,0,298.2,308.7,1408,46.3,3,0
2,0,298.1,308.5,1498,49.4,5,0
3,0,298.2,308.6,1433,39.5,7,0
4,0,298.2,308.7,1408,40.0,9,0
...,...,...,...,...,...,...,...
9995,1,298.8,308.4,1604,29.5,14,0
9996,2,298.9,308.4,1632,31.8,17,0
9997,1,299.0,308.6,1645,33.4,22,0
9998,2,299.0,308.7,1408,48.5,25,0
9999,1,299.0,308.7,1500,40.2,30,0

In [50]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()

In [51]:
df_classification.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,1,298.1,308.6,1551,42.8,0,0
1,0,298.2,308.7,1408,46.3,3,0
2,0,298.1,308.5,1498,49.4,5,0
3,0,298.2,308.6,1433,39.5,7,0
4,0,298.2,308.7,1408,40.0,9,0

In [52]:
num_col = [ 'Air temperature [K]',
    'Process temperature [K]',
    'Rotational speed [rpm]',
    'Torque [Nm]',
    'Tool wear [min]'
]

In [53]:
df_classification[num_col] = scalar.fit_transform(df[num_col])

In [54]:
df_classification.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,1,-0.948880,-0.945448,0.274814,0.228446,-1.699001,0
1,0,-0.898767,-0.877932,-0.827242,0.621715,-1.651815,0
2,0,-0.948880,-1.012964,-0.133640,0.970039,-1.620357,0
3,0,-0.898767,-0.945448,-0.634575,-0.142350,-1.588900,0
4,0,-0.898767,-0.877932,-0.827242,-0.086169,-1.557442,0

In [55]:
df_classification.to_csv("../data/process_classification_data.csv")

In [56]:
print(df_classification['Machine failure'].value_counts())

Machine failure
0    9272
1     263
Name: count, dtype: int64