In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('../data/processed/ordinal_encoding_type_data.csv')

In [4]:
df.head()

,Unnamed: 0,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,0,1,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,1,0,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,2,0,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,3,0,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,4,0,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [5]:
df.drop(['TWF','HDF','PWF','OSF','RNF'], axis=1, inplace=True)

In [6]:
df.head()

,Unnamed: 0,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,0,1,298.1,308.6,1551,42.8,0,0
1,1,0,298.2,308.7,1408,46.3,3,0
2,2,0,298.1,308.5,1498,49.4,5,0
3,3,0,298.2,308.6,1433,39.5,7,0
4,4,0,298.2,308.7,1408,40.0,9,0

In [7]:
df.to_csv("../data/processed/final.csv", index=False)

In [8]:
df = pd.read_csv('../data/processed/final.csv')

In [9]:
df.head()

,Unnamed: 0,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,0,1,298.1,308.6,1551,42.8,0,0
1,1,0,298.2,308.7,1408,46.3,3,0
2,2,0,298.1,308.5,1498,49.4,5,0
3,3,0,298.2,308.6,1433,39.5,7,0
4,4,0,298.2,308.7,1408,40.0,9,0